### PR TITLE
Fix some User Account issues

### LINKED ISSUE #232: Fix preprod issues
Due to our recent preprod deployment, we have some issues to fix (probably more to come) :

- [ ] User menus don't match between the Homepage and the other pages 
- [ ] Edit profile form allows users to change their GitHub or Google ID
- [ ] Edit profile form is not working.

### PR DESCRIPTION
**Pull request by HedicGuibert**
fix #232 

- Fixes the edit profile form
- new homepage matching the rest of the user account better :

homepage

### CODE REVIEW

**Comment by HedicGuibert** [comment]
I noticed that I had forgotten few other things as well (one wrong route, and the PR was removing the logout button), so I fixed that aswell.
This should be good now.

File: src/Form/UserAccount/UserProfileType.php [hunk 1]
```diff
@@ -101,7 +93,7 @@ public function buildForm(FormBuilderInterface $builder, array $options): void
         ;
     }
 
-    /** @return FormInterface|void */
+    /** @return FormInterface|null */
     public function onPasswordSubmit(FormEvent $event): mixed
```
Comment (lyrixx) [inline src/Form/UserAccount/UserProfileType.php:97]: Let's use a real type hint instead of this PHPDoc :/ 

BTW, what's the point to return the form? the return value is never used. let's never return something

File: templates/user/account.html.twig [hunk 2]
```diff
@@ -1,43 +1,9 @@
...
-                    {{ '➡️ Logout' }}
-                </a>
-            </li>
-        </ul>
-    </aside>
-
-    <section class="col-8">
+    {% set section = 'homepage' %}
+    <section class="col-8 mx-auto">
+        {{ parent() }}
```
Comment (lyrixx) [inline templates/user/account.html.twig:6]: Much better 👍🏼

File: src/Form/UserAccount/UserProfileType.php (hunk 1 above)
Comment (HedicGuibert) [reply src/Form/UserAccount/UserProfileType.php:97]: Actually the value is used by the validator. I can't exactly remember where and how, it would require digging, but I'm 100% sure that if I remove the returns and the user submits an invalid form, it breaks.
