### PR TITLE
Fix slack message in double

### LINKED ISSUE #44: Fix double Slack message for added conferences
Sometimes we have Slack message in double for new added conferences. We need to investigate to find why and fix it.

In otherwise, we also have "empty" Slack message with only CFP link as CFP reminder message. May be it is because we do not have conference data? Needs investigation too.

### PR DESCRIPTION
**Pull request by welcoMattic**
Fix #44

### CODE REVIEW

File: src/Event/CfpEndingSoonEvent.php [hunk 1]
```diff
@@ -41,25 +41,26 @@ public function buildAttachment(): array
         $cfpAttachment = SlackNotifier::ATTACHMENT;
         $template = '🔊  CFP for %s (%s) is closing %s';
         $conferenceLink = sprintf('<%s|%s>', $this->conference->getCfpUrl(), $this->conference->getName());
+        $countdown = 'in *' . $this->remainingDays . ' day' . $this->remainingDays > 1 ? 's' : '' . '* !';
```
Comment (Korbeil) [inline src/Event/CfpEndingSoonEvent.php]: et les pluriels hein ? :stuck_out_tongue:

Comment (welcoMattic) [reply src/Event/CfpEndingSoonEvent.php]: Yes, it's mentioned in #47
